# Generated by Django 5.1.11 on 2026-01-06 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_journalentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user'], name='habits_habi_user_id_599ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='habitentry',
            index=models.Index(fields=['habit', 'date'], name='habits_habi_habit_i_3299af_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'date'], name='habits_jour_user_id_1aa2ee_idx'),
        ),
    ]
