# Generated by Django 5.1.11 on 2026-01-06 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_merge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='habitentry',
            index=models.Index(fields=['user', 'date', 'completed'], name='habits_habi_user_id_281a80_idx'),
        ),
    ]
